# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1207, 789)
        MainWindow.setStyleSheet("QWidget {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 0px;\n"
"  color: #E0E1E3;\n"
"  selection-background-color: #346792;\n"
"  selection-color: #E0E1E3;\n"
"    font-family : Ubuntu;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"  selection-background-color: #26486B;\n"
"  selection-color: #9DA9B5;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #176B87;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: rgba(23, 107, 135,50%);\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #60798B;\n"
"  border: 0px solid #1A72BB;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"\n"
"QCheckBox {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"  background-color: rgb(25, 35, 45);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border:#4169E1;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid red;\n"
"}\n"
"QScrollBar:vertical {\n"
"  background-color: rgb(25, 35, 45);\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border: #9FCBFF;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QPushButton{\n"
" /*border:2px solid #05B8CC;*/\n"
" background-color: #176B87;\n"
" color:rgb(255, 255, 255);\n"
" border-radius: 10px;\n"
" font-weight:bold;\n"
" font-size:16px;\n"
"  transition: 500ms;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
" border: 1px solid #176B87;\n"
" background-color: rgba(23, 107, 135,80%)\n"
"}\n"
"QPushButton:pressed {\n"
" margin:1px 2px;\n"
" font-size: 15px;\n"
"}\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QTabBar::tab {\n"
"    background-color: #455364;\n"
"    border: 3px solid #19232D;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: #E0E1E3;\n"
"    font-family: Ubuntu;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #455364;\n"
"    border: 3px solid #19232D;\n"
"    border-radius: 10px;\n"
"    padding: 4px 8px;\n"
"    color: #E0E1E3;\n"
"    font-family: Ubuntu;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color:rgba(69,83,100,60%);\n"
"    color: white;\n"
"    margin-top: 3px;\n"
"    border-bottom: 3px solid white;\n"
"}\n"
"QPlotWidget{\n"
" background-color:(25, 35, 45, 0.8)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_seg = QtWidgets.QWidget()
        self.tab_seg.setObjectName("tab_seg")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_seg)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(25)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_seg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_seg = QtWidgets.QComboBox(self.tab_seg)
        self.comboBox_seg.setStyleSheet("background: #132f5c;")
        self.comboBox_seg.setObjectName("comboBox_seg")
        self.comboBox_seg.addItem("")
        self.comboBox_seg.addItem("")
        self.comboBox_seg.addItem("")
        self.comboBox_seg.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_seg)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_2)
        self.checkBox_LUV = QtWidgets.QCheckBox(self.tab_seg)
        self.checkBox_LUV.setStyleSheet("font-size:16px;")
        self.checkBox_LUV.setObjectName("checkBox_LUV")
        self.horizontalLayout_13.addWidget(self.checkBox_LUV)
        self.stackedWidget_seg = QtWidgets.QStackedWidget(self.tab_seg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_seg.sizePolicy().hasHeightForWidth())
        self.stackedWidget_seg.setSizePolicy(sizePolicy)
        self.stackedWidget_seg.setObjectName("stackedWidget_seg")
        self.page_agglo = QtWidgets.QWidget()
        self.page_agglo.setObjectName("page_agglo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_agglo)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_agglo)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_cluster_size = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_cluster_size.setObjectName("spinBox_cluster_size")
        self.horizontalLayout_6.addWidget(self.spinBox_cluster_size)
        self.gridLayout_9.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBox_cluster_init = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_cluster_init.setObjectName("spinBox_cluster_init")
        self.horizontalLayout_9.addWidget(self.spinBox_cluster_init)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget_seg.addWidget(self.page_agglo)
        self.page_mean_shift = QtWidgets.QWidget()
        self.page_mean_shift.setObjectName("page_mean_shift")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_mean_shift)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_mean_shift)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spinBox_cluster_size_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_cluster_size_2.setObjectName("spinBox_cluster_size_2")
        self.horizontalLayout_10.addWidget(self.spinBox_cluster_size_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.spinBox_cluster_init_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_cluster_init_2.setObjectName("spinBox_cluster_init_2")
        self.horizontalLayout_11.addWidget(self.spinBox_cluster_init_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget_seg.addWidget(self.page_mean_shift)
        self.page_kmeans = QtWidgets.QWidget()
        self.page_kmeans.setObjectName("page_kmeans")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_kmeans)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_kmeans)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_2.setContentsMargins(-1, 25, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setStyleSheet("font-size:15px;")
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sld_seg_ksize = QtWidgets.QSlider(self.groupBox_4)
        self.sld_seg_ksize.setMinimum(3)
        self.sld_seg_ksize.setMaximum(12)
        self.sld_seg_ksize.setPageStep(2)
        self.sld_seg_ksize.setProperty("value", 3)
        self.sld_seg_ksize.setOrientation(QtCore.Qt.Horizontal)
        self.sld_seg_ksize.setObjectName("sld_seg_ksize")
        self.horizontalLayout_7.addWidget(self.sld_seg_ksize)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setMinimumSize(QtCore.QSize(50, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setStyleSheet("font-size:15px;")
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sld_seg_max_iterations = QtWidgets.QSlider(self.groupBox_4)
        self.sld_seg_max_iterations.setMinimum(50)
        self.sld_seg_max_iterations.setMaximum(100)
        self.sld_seg_max_iterations.setProperty("value", 50)
        self.sld_seg_max_iterations.setOrientation(QtCore.Qt.Horizontal)
        self.sld_seg_max_iterations.setObjectName("sld_seg_max_iterations")
        self.horizontalLayout_8.addWidget(self.sld_seg_max_iterations)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setMinimumSize(QtCore.QSize(50, 0))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.stackedWidget_seg.addWidget(self.page_kmeans)
        self.page_region_grow = QtWidgets.QWidget()
        self.page_region_grow.setObjectName("page_region_grow")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_region_grow)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_region_grow)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("font-size:15px;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sld_region_threshold = QtWidgets.QSlider(self.groupBox_3)
        self.sld_region_threshold.setMinimum(1)
        self.sld_region_threshold.setMaximum(50)
        self.sld_region_threshold.setProperty("value", 6)
        self.sld_region_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.sld_region_threshold.setObjectName("sld_region_threshold")
        self.horizontalLayout.addWidget(self.sld_region_threshold)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.stackedWidget_seg.addWidget(self.page_region_grow)
        self.horizontalLayout_13.addWidget(self.stackedWidget_seg)
        self.btn_seg_apply = QtWidgets.QPushButton(self.tab_seg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btn_seg_apply.sizePolicy().hasHeightForWidth())
        self.btn_seg_apply.setSizePolicy(sizePolicy)
        self.btn_seg_apply.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_seg_apply.setObjectName("btn_seg_apply")
        self.horizontalLayout_13.addWidget(self.btn_seg_apply)
        self.gridLayout_10.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.wgt_seg_input = PlotWidget(self.tab_seg)
        self.wgt_seg_input.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_seg_input.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_seg_input.setStyleSheet("background: crimson;")
        self.wgt_seg_input.setObjectName("wgt_seg_input")
        self.horizontalLayout_12.addWidget(self.wgt_seg_input)
        self.wgt_seg_output = PlotWidget(self.tab_seg)
        self.wgt_seg_output.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_seg_output.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_seg_output.setStyleSheet("background: deep blue;")
        self.wgt_seg_output.setObjectName("wgt_seg_output")
        self.horizontalLayout_12.addWidget(self.wgt_seg_output)
        self.gridLayout_10.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_10.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_seg, "")
        self.tab_thresh = QtWidgets.QWidget()
        self.tab_thresh.setObjectName("tab_thresh")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_thresh)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(25)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.tab_thresh)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.comboBox_seg_2 = QtWidgets.QComboBox(self.tab_thresh)
        self.comboBox_seg_2.setStyleSheet("background: #132f5c;")
        self.comboBox_seg_2.setObjectName("comboBox_seg_2")
        self.comboBox_seg_2.addItem("")
        self.comboBox_seg_2.addItem("")
        self.comboBox_seg_2.addItem("")
        self.comboBox_seg_2.addItem("")
        self.comboBox_seg_2.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_seg_2)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.stackedWidget_seg_2 = QtWidgets.QStackedWidget(self.tab_thresh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_seg_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_seg_2.setSizePolicy(sizePolicy)
        self.stackedWidget_seg_2.setObjectName("stackedWidget_seg_2")
        self.page_agglo_2 = QtWidgets.QWidget()
        self.page_agglo_2.setObjectName("page_agglo_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_agglo_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_agglo_2)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setStyleSheet("font-size:15px;")
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sld_thresh_global_max = QtWidgets.QSlider(self.groupBox_5)
        self.sld_thresh_global_max.setMinimum(0)
        self.sld_thresh_global_max.setMaximum(100)
        self.sld_thresh_global_max.setProperty("value", 20)
        self.sld_thresh_global_max.setOrientation(QtCore.Qt.Horizontal)
        self.sld_thresh_global_max.setObjectName("sld_thresh_global_max")
        self.horizontalLayout_5.addWidget(self.sld_thresh_global_max)
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setMinimumSize(QtCore.QSize(25, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setStyleSheet("font-size:15px;")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setStyleSheet("font-size:15px;")
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sld_thresh_global_min = QtWidgets.QSlider(self.groupBox_5)
        self.sld_thresh_global_min.setMinimum(0)
        self.sld_thresh_global_min.setMaximum(100)
        self.sld_thresh_global_min.setProperty("value", 30)
        self.sld_thresh_global_min.setOrientation(QtCore.Qt.Horizontal)
        self.sld_thresh_global_min.setObjectName("sld_thresh_global_min")
        self.horizontalLayout_3.addWidget(self.sld_thresh_global_min)
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setMinimumSize(QtCore.QSize(25, 0))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setStyleSheet("font-size:15px;")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout_7.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.stackedWidget_seg_2.addWidget(self.page_agglo_2)
        self.page_mean_shift_2 = QtWidgets.QWidget()
        self.page_mean_shift_2.setObjectName("page_mean_shift_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_mean_shift_2)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_mean_shift_2)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setContentsMargins(-1, 25, -1, -1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sld_thresh_local_block_size = QtWidgets.QSlider(self.groupBox_6)
        self.sld_thresh_local_block_size.setMinimum(3)
        self.sld_thresh_local_block_size.setMaximum(7)
        self.sld_thresh_local_block_size.setSingleStep(2)
        self.sld_thresh_local_block_size.setPageStep(2)
        self.sld_thresh_local_block_size.setProperty("value", 3)
        self.sld_thresh_local_block_size.setOrientation(QtCore.Qt.Horizontal)
        self.sld_thresh_local_block_size.setObjectName("sld_thresh_local_block_size")
        self.horizontalLayout_4.addWidget(self.sld_thresh_local_block_size)
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setMinimumSize(QtCore.QSize(25, 0))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setStyleSheet("font-size:15px;")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("font-size:15px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.stackedWidget_seg_2.addWidget(self.page_mean_shift_2)
        self.page_kmeans_2 = QtWidgets.QWidget()
        self.page_kmeans_2.setObjectName("page_kmeans_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_kmeans_2)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.stackedWidget_seg_2.addWidget(self.page_kmeans_2)
        self.page_region_grow_2 = QtWidgets.QWidget()
        self.page_region_grow_2.setObjectName("page_region_grow_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_region_grow_2)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.stackedWidget_seg_2.addWidget(self.page_region_grow_2)
        self.horizontalLayout_15.addWidget(self.stackedWidget_seg_2)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.btn_thresh_apply = QtWidgets.QPushButton(self.tab_thresh)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btn_thresh_apply.sizePolicy().hasHeightForWidth())
        self.btn_thresh_apply.setSizePolicy(sizePolicy)
        self.btn_thresh_apply.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_thresh_apply.setObjectName("btn_thresh_apply")
        self.horizontalLayout_15.addWidget(self.btn_thresh_apply)
        self.gridLayout_16.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.wgt_thresh_input = PlotWidget(self.tab_thresh)
        self.wgt_thresh_input.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_thresh_input.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_thresh_input.setStyleSheet("background: crimson;")
        self.wgt_thresh_input.setObjectName("wgt_thresh_input")
        self.horizontalLayout_14.addWidget(self.wgt_thresh_input)
        self.wgt_thresh_output = PlotWidget(self.tab_thresh)
        self.wgt_thresh_output.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_thresh_output.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_thresh_output.setStyleSheet("background: deep blue;")
        self.wgt_thresh_output.setObjectName("wgt_thresh_output")
        self.horizontalLayout_14.addWidget(self.wgt_thresh_output)
        self.gridLayout_16.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.gridLayout_16.setRowStretch(1, 1)
        self.tabWidget.addTab(self.tab_thresh, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget_seg.setCurrentIndex(0)
        self.stackedWidget_seg_2.setCurrentIndex(0)
        self.sld_seg_ksize.valueChanged['int'].connect(self.label_12.setNum) # type: ignore
        self.sld_seg_max_iterations.valueChanged['int'].connect(self.label_13.setNum) # type: ignore
        self.comboBox_seg.currentIndexChanged['int'].connect(self.stackedWidget_seg.setCurrentIndex) # type: ignore
        self.sld_thresh_global_max.valueChanged['int'].connect(self.label_24.setNum) # type: ignore
        self.sld_thresh_global_min.valueChanged['int'].connect(self.label_25.setNum) # type: ignore
        self.comboBox_seg_2.currentIndexChanged['int'].connect(self.stackedWidget_seg_2.setCurrentIndex) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Segmentation Method"))
        self.comboBox_seg.setItemText(0, _translate("MainWindow", "Agglomerative"))
        self.comboBox_seg.setItemText(1, _translate("MainWindow", "Mean Shift"))
        self.comboBox_seg.setItemText(2, _translate("MainWindow", "K-Means"))
        self.comboBox_seg.setItemText(3, _translate("MainWindow", "Region Growing"))
        self.checkBox_LUV.setText(_translate("MainWindow", "LUV"))
        self.groupBox.setTitle(_translate("MainWindow", "Agglo. Settings"))
        self.label_6.setText(_translate("MainWindow", "Cluster Size:"))
        self.label_9.setText(_translate("MainWindow", "Init Cluster:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mean Shift Settings"))
        self.label_10.setText(_translate("MainWindow", "Cluster Size:"))
        self.label_11.setText(_translate("MainWindow", "Init Cluster:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "K-Means Settings"))
        self.label_7.setText(_translate("MainWindow", "K-Size"))
        self.label_12.setText(_translate("MainWindow", "3"))
        self.label_8.setText(_translate("MainWindow", "Max Iterations"))
        self.label_13.setText(_translate("MainWindow", "12"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Region Grow Settings"))
        self.label.setText(_translate("MainWindow", "Region Threshold"))
        self.btn_seg_apply.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_seg), _translate("MainWindow", "Segmentation"))
        self.label_14.setText(_translate("MainWindow", "Thresholding Method"))
        self.comboBox_seg_2.setItemText(0, _translate("MainWindow", "Global"))
        self.comboBox_seg_2.setItemText(1, _translate("MainWindow", "Local"))
        self.comboBox_seg_2.setItemText(2, _translate("MainWindow", "Optimal"))
        self.comboBox_seg_2.setItemText(3, _translate("MainWindow", "Otsu"))
        self.comboBox_seg_2.setItemText(4, _translate("MainWindow", "Multilevel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Global Threshold Settings"))
        self.label_3.setText(_translate("MainWindow", "Max Threshold"))
        self.label_24.setText(_translate("MainWindow", "20"))
        self.label_4.setText(_translate("MainWindow", "Min Threshold"))
        self.label_25.setText(_translate("MainWindow", "30"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Local Threshold Settings"))
        self.label_26.setText(_translate("MainWindow", "3"))
        self.label_5.setText(_translate("MainWindow", "Block Size"))
        self.btn_thresh_apply.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_thresh), _translate("MainWindow", "Thresholding"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen_Image.setShortcut(_translate("MainWindow", "Ctrl+O"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
